<?php
    //General
    require_once __DIR__.'/classes/config_class.php';

    $configPath = __DIR__.'/config/config.ini';
    $config = new configClass($configPath); //or die('{"Error":2,"Info":"No config file"}');
    //$debug = $config->getParameter("General","debugMode");

    /*if($debug){
        ini_set('display_startup_errors', 1);
        ini_set('display_errors', 1);
        error_reporting(-1);
    } */

    require_once __DIR__."/php/login.php";    
    
?>


<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">

        <title>SG-OS</title>
        
        <!--MetaTags -> Immer Benutzen-->
        <meta content="IE=edge" http-equiv="X-UA-Compatible" />
        <meta name="viewport" content="width=device-width,initial-scale=1"  />
  
        <!--MetaTags-->
        <link rel="stylesheet" type="text/css" href="./css/styles.css" />
        <!--<link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet"> -->
    </head>
    <body id="main-background">

        <header class="header">            
        </header>      
        <div class="container">
            <div class="row border">
                <div class="late-login">
                
                    <form action="index.php?" method="POST">
                    <p><input name="username" id="username" class="cyberbutton" type="text" placeholder="Name"  /></p>
                    <p><input name="password" id="password" class="cyberbutton" type="password" placeholder="Password"  /></p>
                    <input type="hidden" id="login" name="login" value="1">
                    <p><input class="cyberbutton hiddenbutton" type="submit" value="login"/></p>
                    </form>
                    <?php 
                    if(isset($returnMessage)) {
                        echo $returnMessage;
                    }    
                    if(isset($_GET["no_access"])){
                        if($_GET["no_access"]==1){
                            echo "<p class='typewriter text-to-center'>No Dat░█▜▧▓</p>";
                        }elseif($_GET["no_access"]==2){
                            echo "<p class='typewriter text-to-center'>█▓▜░▧!ccess</p>";
                        }
                    }                                         
                    ?>                

                </div>
            <code><span class="ascii typewriter" style="color: green; background: black;
display:inline-block;
white-space:pre;
letter-spacing:0;
line-height:1.4;
font-family:'Consolas','BitstreamVeraSansMono','CourierNew',Courier,monospace;
font-size:12px;
margin-left: 45px;
border-width:0px;
border-style:solid;
border-color:lightgray;
"><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span>
<span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span>
<span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span>/</span><span>.</span><span> </span><span>(</span><span>.</span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span>/</span><span>@</span><span>@</span><span>@</span><span>@</span><span>.</span><span>&</span><span>*</span><span> </span><span>&</span><span>/</span><span> </span><span>@</span><span>@</span><span>#</span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span>@</span><span>&</span><span>@</span><span>.</span><span>*</span><span>@</span><span>.</span><span>*</span><span>&</span><span>.</span><span>@</span><span>@</span><span>@</span><span>@</span><span>(</span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span>/</span><span>.</span><span> </span><span> </span><span>(</span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span>
<span> </span><span> </span><span> </span><span> </span><span> </span><span>*</span><span>*</span><span>*</span><span>*</span><span>/</span><span>.</span><span> </span><span>.</span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span>&</span><span>,</span><span>(</span><span>.</span><span>(</span><span> </span><span>,</span><span>/</span><span> </span><span>/</span><span>%</span><span>.</span><span>#</span><span>&</span><span>@</span><span>/</span><span>#</span><span>/</span><span>%</span><span>.</span><span>(</span><span>#</span><span>(</span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span>/</span><span>#</span><span>*</span><span>,</span><span>(</span><span>(</span><span>%</span><span>*</span><span>@</span><span>&</span><span>%</span><span>,</span><span>(</span><span>#</span><span> </span><span>*</span><span>(</span><span> </span><span>(</span><span>.</span><span>/</span><span>*</span><span>&</span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span>(</span><span> </span><span>(</span><span>(</span><span>,</span><span>,</span><span>,</span><span>,</span><span> </span><span> </span><span> </span><span> </span><span> </span>
<span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span>.</span><span>.</span><span>.</span><span>%</span><span> </span><span> </span><span> </span><span> </span><span> </span><span>@</span><span>.</span><span>#</span><span> </span><span>(</span><span> </span><span>.</span><span>#</span><span> </span><span>*</span><span>#</span><span> </span><span>%</span><span>.</span><span> </span><span>/</span><span>.</span><span>/</span><span>*</span><span>,</span><span>,</span><span>.</span><span>(</span><span>#</span><span>&</span><span>@</span><span>.</span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span>@</span><span>%</span><span>/</span><span>/</span><span>,</span><span>/</span><span>*</span><span>*</span><span>(</span><span>*</span><span>(</span><span> </span><span> </span><span>&</span><span> </span><span>*</span><span>(</span><span> </span><span>%</span><span> </span><span> </span><span>#</span><span> </span><span>@</span><span> </span><span>@</span><span>.</span><span> </span><span> </span><span> </span><span>%</span><span>,</span><span>,</span><span>,</span><span>.</span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span>
<span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span>(</span><span>&</span><span>/</span><span>#</span><span> </span><span>&</span><span> </span><span>,</span><span>*</span><span>(</span><span>,</span><span>.</span><span>,</span><span> </span><span>(</span><span> </span><span>,</span><span>.</span><span> </span><span>&</span><span> </span><span> </span><span>/</span><span>.</span><span>,</span><span>@</span><span>(</span><span>(</span><span>@</span><span> </span><span>%</span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span>(</span><span> </span><span>%</span><span>*</span><span>%</span><span>%</span><span>.</span><span>*</span><span>,</span><span>.</span><span> </span><span>@</span><span> </span><span> </span><span>(</span><span> </span><span>*</span><span> </span><span>.</span><span>/</span><span> </span><span>%</span><span>/</span><span>.</span><span> </span><span>#</span><span> </span><span>%</span><span>.</span><span>&</span><span>,</span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span>
<span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span>(</span><span>/</span><span>/</span><span>@</span><span>*</span><span>.</span><span>%</span><span> </span><span>/</span><span>#</span><span>/</span><span>#</span><span>*</span><span>#</span><span>.</span><span>%</span><span>/</span><span>#</span><span> </span><span>(</span><span> </span><span> </span><span>/</span><span> </span><span> </span><span>/</span><span>,</span><span>/</span><span>#</span><span>%</span><span>%</span><span>/</span><span>@</span><span>*</span><span>.</span><span>.</span><span>.</span><span>.</span><span>.</span><span>,</span><span>@</span><span>,</span><span>%</span><span>*</span><span>(</span><span>(</span><span>,</span><span>/</span><span> </span><span> </span><span>#</span><span> </span><span> </span><span>/</span><span> </span><span>(</span><span>(</span><span>&</span><span>*</span><span>&</span><span>(</span><span>(</span><span>(</span><span>#</span><span>,</span><span> </span><span>@</span><span> </span><span>(</span><span>%</span><span>.</span><span>/</span><span>%</span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span>
<span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span>.</span><span>%</span><span>*</span><span>*</span><span> </span><span>,</span><span>#</span><span>.</span><span>&</span><span>,</span><span>,</span><span>*</span><span>#</span><span>#</span><span>(</span><span>*</span><span>@</span><span>&</span><span>,</span><span>,</span><span>*</span><span>@</span><span>/</span><span>,</span><span>.</span><span> </span><span>(</span><span> </span><span> </span><span>&</span><span>,</span><span>*</span><span> </span><span> </span><span>.</span><span> </span><span> </span><span>*</span><span>,</span><span> </span><span>.</span><span>/</span><span>.</span><span> </span><span>,</span><span>@</span><span> </span><span> </span><span>,</span><span>.</span><span> </span><span>/</span><span>*</span><span>@</span><span>,</span><span>*</span><span>.</span><span>@</span><span>@</span><span>,</span><span>/</span><span>/</span><span>(</span><span>,</span><span>/</span><span>/</span><span>#</span><span> </span><span>&</span><span>.</span><span>.</span><span>(</span><span>.</span><span>#</span><span>,</span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span>
<span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span>/</span><span>*</span><span>*</span><span>.</span><span>,</span><span>*</span><span>(</span><span> </span><span>&</span><span>(</span><span>@</span><span>*</span><span>*</span><span>*</span><span>&</span><span>@</span><span>@</span><span>@</span><span>&</span><span>(</span><span>@</span><span>,</span><span>.</span><span>,</span><span>,</span><span>,</span><span>(</span><span>#</span><span>,</span><span>,</span><span> </span><span>%</span><span>#</span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span>(</span><span>&</span><span> </span><span>.</span><span>*</span><span>/</span><span>&</span><span>,</span><span>.</span><span>,</span><span>,</span><span>.</span><span>@</span><span>#</span><span>&</span><span>@</span><span>@</span><span>@</span><span>&</span><span>#</span><span>(</span><span>/</span><span>@</span><span>#</span><span>@</span><span>.</span><span>#</span><span>,</span><span>.</span><span>*</span><span>,</span><span>(</span><span>%</span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span>
<span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span>%</span><span>*</span><span>.</span><span>#</span><span>#</span><span> </span><span>/</span><span>/</span><span>(</span><span>(</span><span>@</span><span>@</span><span>&</span><span>,</span><span>,</span><span> </span><span> </span><span> </span><span> </span><span>,</span><span>%</span><span>@</span><span>@</span><span>@</span><span>*</span><span>*</span><span>,</span><span>%</span><span> </span><span>*</span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span>.</span><span>.</span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span>,</span><span> </span><span>*</span><span>,</span><span>/</span><span>,</span><span>@</span><span>@</span><span>@</span><span>&</span><span>,</span><span> </span><span> </span><span> </span><span>.</span><span>/</span><span> </span><span>#</span><span>@</span><span>@</span><span>(</span><span>/</span><span>#</span><span>*</span><span> </span><span>&</span><span>#</span><span>,</span><span>*</span><span>&</span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span>
<span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span>%</span><span> </span><span> </span><span>#</span><span> </span><span>#</span><span>#</span><span>*</span><span>(</span><span>&</span><span>@</span><span>,</span><span> </span><span> </span><span> </span><span> </span><span>*</span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span>@</span><span>*</span><span>(</span><span>@</span><span>(</span><span>.</span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span>.</span><span>.</span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span>.</span><span>*</span><span>%</span><span>(</span><span>*</span><span>%</span><span>.</span><span> </span><span> </span><span> </span><span> </span><span>#</span><span> </span><span> </span><span> </span><span> </span><span> </span><span>,</span><span>@</span><span>@</span><span>,</span><span>/</span><span>/</span><span>(</span><span>.</span><span>%</span><span> </span><span> </span><span>%</span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span>
<span> </span><span>*</span><span>(</span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span>/</span><span>&</span><span>,</span><span> </span><span>,</span><span>/</span><span>*</span><span>,</span><span>*</span><span>,</span><span>/</span><span>/</span><span>(</span><span>@</span><span>(</span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span>(</span><span> </span><span> </span><span>,</span><span>@</span><span>&</span><span>@</span><span>#</span><span>,</span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span>&</span><span>*</span><span>&</span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span>.</span><span>%</span><span>&</span><span>(</span><span>@</span><span>.</span><span>,</span><span>(</span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span>,</span><span>@</span><span>%</span><span>(</span><span>/</span><span>*</span><span>*</span><span>,</span><span>/</span><span>*</span><span>/</span><span> </span><span>.</span><span>&</span><span>#</span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span>*</span><span>(</span>
<span> </span><span> </span><span>/</span><span>@</span><span>@</span><span>*</span><span>,</span><span>.</span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span>%</span><span>@</span><span>&</span><span>%</span><span>#</span><span>*</span><span>#</span><span>@</span><span>@</span><span>,</span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span>(</span><span>&</span><span>@</span><span>&</span><span>*</span><span>,</span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span>#</span><span>*</span><span>(</span><span>.</span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span>.</span><span>*</span><span>%</span><span>@</span><span>@</span><span>*</span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span>.</span><span>@</span><span>@</span><span>#</span><span>,</span><span>(</span><span>%</span><span>&</span><span>@</span><span>&</span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span>.</span><span>,</span><span>(</span><span>@</span><span>@</span><span>#</span><span> </span>
<span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span>#</span><span>@</span><span>/</span><span>/</span><span>,</span><span>/</span><span>.</span><span>.</span><span> </span><span> </span><span>@</span><span>&</span><span>(</span><span>@</span><span>@</span><span>@</span><span>#</span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span>(</span><span>,</span><span>&</span><span>@</span><span>,</span><span> </span><span> </span><span> </span><span> </span><span> </span><span>,</span><span>/</span><span> </span><span> </span><span>&</span><span> </span><span>&</span><span> </span><span> </span><span>,</span><span>,</span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span>@</span><span>&</span><span>(</span><span>#</span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span>*</span><span>@</span><span>@</span><span>@</span><span>(</span><span>&</span><span>@</span><span> </span><span> </span><span>.</span><span>,</span><span>/</span><span>,</span><span>*</span><span>(</span><span>@</span><span>%</span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span>
<span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span>*</span><span>@</span><span>/</span><span>(</span><span>(</span><span>,</span><span>.</span><span>*</span><span>(</span><span>#</span><span>@</span><span>@</span><span>@</span><span>@</span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span>.</span><span>.</span><span>.</span><span>.</span><span>,</span><span> </span><span> </span><span> </span><span> </span><span>@</span><span>#</span><span> </span><span> </span><span> </span><span>&</span><span> </span><span>%</span><span> </span><span> </span><span> </span><span>/</span><span>@</span><span>,</span><span> </span><span> </span><span> </span><span>*</span><span> </span><span> </span><span> </span><span>(</span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span>@</span><span>@</span><span>@</span><span>@</span><span>%</span><span>#</span><span>,</span><span> </span><span>,</span><span>(</span><span>/</span><span>,</span><span>@</span><span>*</span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span>
<span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span>@</span><span>(</span><span>,</span><span>/</span><span> </span><span>,</span><span> </span><span>.</span><span>%</span><span>@</span><span>@</span><span>#</span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span>*</span><span>.</span><span>.</span><span>(</span><span>%</span><span>*</span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span>.</span><span> </span><span>.</span><span>#</span><span>/</span><span>.</span><span> </span><span>%</span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span>#</span><span>@</span><span>@</span><span>&</span><span> </span><span> </span><span>*</span><span> </span><span>*</span><span>*</span><span>/</span><span>@</span><span>.</span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span>
<span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span>@</span><span>/</span><span>*</span><span>*</span><span>*</span><span>/</span><span>.</span><span>.</span><span>%</span><span>@</span><span>&</span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span>#</span><span>(</span><span>%</span><span>,</span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span>(</span><span>#</span><span>(</span><span>#</span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span>#</span><span>@</span><span>%</span><span>.</span><span>.</span><span>#</span><span>*</span><span>,</span><span>/</span><span>,</span><span>@</span><span>.</span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span>
<span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span>(</span><span>@</span><span>*</span><span>*</span><span>.</span><span>,</span><span>*</span><span>*</span><span>/</span><span>%</span><span>@</span><span>,</span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span>,</span><span> </span><span> </span><span> </span><span>*</span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span>.</span><span> </span><span> </span><span> </span><span>%</span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span>.</span><span>@</span><span>@</span><span>*</span><span>,</span><span>,</span><span>,</span><span>/</span><span>*</span><span>,</span><span>@</span><span>%</span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span>
<span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span>@</span><span>%</span><span>#</span><span>.</span><span>*</span><span> </span><span>,</span><span>/</span><span>(</span><span>%</span><span>*</span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span>*</span><span>,</span><span>(</span><span> </span><span>#</span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span>#</span><span> </span><span>#</span><span>*</span><span>%</span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span>.</span><span>&</span><span>*</span><span>,</span><span>,</span><span>.</span><span>*</span><span> </span><span>#</span><span>#</span><span>@</span><span>,</span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span>
<span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span>(</span><span>@</span><span>#</span><span>(</span><span>&</span><span>@</span><span>@</span><span>*</span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span>/</span><span>,</span><span>*</span><span>(</span><span>,</span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span>.</span><span>*</span><span>,</span><span>(</span><span>%</span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span>,</span><span>@</span><span>@</span><span>&</span><span>#</span><span>%</span><span>&</span><span>#</span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span>
<span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span>#</span><span>.</span><span>@</span><span>@</span><span>#</span><span> </span><span>@</span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span>@</span><span>.</span><span>#</span><span>@</span><span>@</span><span>.</span><span>@</span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span>
<span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span>(</span><span> </span><span> </span><span>.</span><span>,</span><span>@</span><span>#</span><span>/</span><span>%</span><span>#</span><span> </span><span> </span><span> </span><span> </span><span> </span><span>&</span><span>*</span><span>#</span><span>%</span><span>%</span><span> </span><span>/</span><span> </span><span>(</span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span>
<span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span>(</span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span>#</span><span>.</span><span>*</span><span> </span><span>@</span><span>%</span><span>@</span><span>,</span><span> </span><span>.</span><span>@</span><span>#</span><span>@</span><span> </span><span>,</span><span>/</span><span>&</span><span> </span><span> </span><span> </span><span> </span><span> </span><span>(</span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span>
<span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span>@</span><span> </span><span> </span><span>/</span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span>%</span><span> </span><span>&</span><span>@</span><span>@</span><span>@</span><span>*</span><span>@</span><span>@</span><span>@</span><span>%</span><span> </span><span>#</span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span>(</span><span> </span><span> </span><span>#</span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span>
<span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span>/</span><span>@</span><span>@</span><span>@</span><span>@</span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span>,</span><span>.</span><span> </span><span>.</span><span>/</span><span>%</span><span>(</span><span>%</span><span>#</span><span>.</span><span>,</span><span> </span><span>%</span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span>&</span><span>@</span><span>@</span><span>@</span><span>%</span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span>
<span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span>@</span><span>@</span><span>@</span><span>*</span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span>%</span><span> </span><span>*</span><span>*</span><span>@</span><span>#</span><span>%</span><span>/</span><span>*</span><span> </span><span>/</span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span>*</span><span>&</span><span>@</span><span>@</span><span>.</span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span>
<span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span>@</span><span>#</span><span>#</span><span>*</span><span>@</span><span>,</span><span> </span><span>#</span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span>
<span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span>&</span><span> </span><span>#</span><span> </span><span>#</span><span> </span><span>%</span><span> </span><span>*</span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span>
<span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span>#</span><span>%</span><span>%</span><span>,</span><span>%</span><span>.</span><span>,</span><span>%</span><span>@</span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span>
<span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span>
</span></code>
            </div>          
        </div>                   
    </body>    
</html>